id = "storm_elemental"
name = "Storm Elemental"
card_type = "Creature"
cost = "4"
description = "Flying. When Storm Elemental enters the battlefield, deal 2 damage to target creature."

[stats]
power = "3"
toughness = "2"
